import Head from 'next/head'
import {
    NextPage,
    GetStaticProps, GetStaticPropsContext, InferGetStaticPropsType
} from 'next'
import { Inter } from '@next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })
import getWeather, {ForeCastsResponse, ForeCast, GetWeatherParams} from "@Requests/getWeather";
import styles from '@Styles/[lon].module.css';

type ForeCastsProps = {
    forecasts: ForeCastsResponse
}
export async function getStaticPaths() {
    const params: GetWeatherParams[] = [
        {
            lat: '36',
            lon: '46'
        },
        {
            lat: '48',
            lon: '57'
        },
    ];

    return {
        paths: params.map(({lat, lon}) => {
            return {
                params: {
                    lat,
                    lon,
                },
            };
        }),
        fallback: false,
    };
}
/**
 * Instead of fetching your `/api` route you can call the same
 * function directly in `getStaticProps`
 * @param context
 */
export const getStaticProps: GetStaticProps = async (context: GetStaticPropsContext) => {
    const response = await getWeather(context.params as GetWeatherParams)
    const forecasts = response.data

    return {
        props: {
            forecasts
        },
    }
}

const StaticForeCasts: NextPage<ForeCastsProps> = ({ forecasts }: InferGetStaticPropsType<typeof getStaticProps>) => {

    // console.log('StaticForeCasts::render - forecasts: ', forecasts)

    return (
        <>
            <Head>
                <title>Forecasts</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.grid}>

                {
                    forecasts.data?.map((f: ForeCast) => {
                        return (
                            <Link
                                key={f.ts}
                                href={`/forecasts/${f.ts}`}
                                className={styles.card}
                                target="_blank"
                                rel="noopener noreferrer"
                            >
                                <h2 className={inter.className}>
                                    Wind direction: {f.wind_cdir}
                                </h2>
                                <p className={inter.className}>
                                    Desc: {f.weather.description}
                                </p>
                            </Link>
                        )
                    })
                }

                </div>
            </main>
        </>
    )
}

export default StaticForeCasts