// List of ten locations remapped current observations
const currentDefaultObservations: GetCurrentDefaultObservationsResponse = [
  {
    cityName: 'Leh',
    weatherDescription: 'Overcast clouds',
    weatherIcon: 'c04n',
    sunrise: { date: '01:30', formatted: '7:30am' },
    sunset: { date: '12:31', formatted: '6:31pm' },
    temperature: '-41.8°',
    coordinates: { lat: '35.5', lon: '78.5' },
  },
  {
    cityName: 'Lille',
    weatherDescription: 'Few clouds',
    weatherIcon: 'c02n',
    sunrise: { date: '06:48', formatted: '7:48am' },
    sunset: { date: '17:13', formatted: '6:13pm' },
    temperature: '8.9°',
    coordinates: { lat: '50.6302', lon: '3.0598' },
  },
  {
    cityName: 'El Pardo',
    weatherDescription: 'Overcast clouds',
    weatherIcon: 'c04d',
    sunrise: { date: '07:00', formatted: '8:00am' },
    sunset: { date: '17:55', formatted: '6:55pm' },
    temperature: '17.8°',
    coordinates: { lat: '40.5184', lon: '-3.8252' },
  },
  {
    cityName: 'Rome',
    weatherDescription: 'Few clouds',
    weatherIcon: 'c02n',
    sunrise: { date: '05:57', formatted: '6:57am' },
    sunset: { date: '16:50', formatted: '5:50pm' },
    temperature: '15°',
    coordinates: { lat: '41.9125', lon: '12.5085' },
  },
  {
    cityName: 'City of London',
    weatherDescription: 'Broken clouds',
    weatherIcon: 'c03d',
    sunrise: { date: '07:02', formatted: '7:02am' },
    sunset: { date: '17:24', formatted: '5:24pm' },
    temperature: '12.8°',
    coordinates: { lat: '51.5066', lon: '-0.1039' },
  },
  {
    cityName: 'Little Italy',
    weatherDescription: 'Overcast clouds',
    weatherIcon: 'c04d',
    sunrise: { date: '11:41', formatted: '6:41am' },
    sunset: { date: '22:36', formatted: '5:36pm' },
    temperature: '10.4°',
    coordinates: { lat: '40.725', lon: '-73.9906' },
  },
  {
    cityName: 'Tokyo',
    weatherDescription: 'Broken clouds',
    weatherIcon: 'c03n',
    sunrise: { date: '21:21', formatted: '6:21am' },
    sunset: { date: '08:28', formatted: '5:28pm' },
    temperature: '-0.8°',
    coordinates: { lat: '35.6892', lon: '139.7624' },
  },
  {
    cityName: 'Buenos Aires',
    weatherDescription: 'Clear sky',
    weatherIcon: 'c01d',
    sunrise: { date: '09:33', formatted: '6:33am' },
    sunset: { date: '22:41', formatted: '7:41pm' },
    temperature: '27.6°',
    coordinates: { lat: '-34.6282', lon: '-58.447' },
  },
]

export default currentDefaultObservations
