import Head from 'next/head'
import type {
  GetStaticProps,
  GetStaticPropsContext,
  InferGetStaticPropsType,
} from 'next'
import type { ReactElement } from 'react'
import type { NextPageWithLayout } from '@Routes/_app'
import getWeather, {
  ForeCastsResponse,
  ForeCast,
  GetWeatherParams,
} from '@Requests/getWeather'
import MainLayout from '@Layouts/MainLayout'
import Grid from '@Components/Grid'
import ClickableCard from '@Components/ClickableCard'
import GoogleMapsWrapper from '@Components/GoogleMaps/GoogleMapsWrapper'
import Map from '@Components/GoogleMaps/Map'

type ForeCastsProps = {
  forecasts: ForeCastsResponse
}
export async function getStaticPaths() {
  const params: GetWeatherParams[] = [
    {
      lat: '36',
      lon: '46',
    },
    {
      lat: '48',
      lon: '57',
    },
  ]

  return {
    paths: params.map(({ lat, lon }) => ({
      params: {
        lat,
        lon,
      },
    })),
    fallback: false,
  }
}
/**
 * Instead of fetching your `/api` route you can call the same
 * function directly in `getStaticProps`
 * @param context
 */
export const getStaticProps: GetStaticProps = async (
  context: GetStaticPropsContext
) => {
  const response = await getWeather(context.params as GetWeatherParams)
  const forecasts = response.data

  return {
    props: {
      forecasts,
    },
  }
}

const StaticForeCasts: NextPageWithLayout<ForeCastsProps> = ({
  forecasts,
}: InferGetStaticPropsType<typeof getStaticProps>) => (
  <>
    <Head>
      <title>Forecasts - Generated page with no Google Map</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>Generated page with no Google Map</div>
    <GoogleMapsWrapper
      apiKey={process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY as string}
    >
      <Map />
    </GoogleMapsWrapper>
    <Grid>
      {forecasts.data?.map((f: ForeCast) => (
        <ClickableCard
          key={f.ts}
          href={`/forecasts/${f.ts}`}
          title={<>Wind direction: {f.wind_cdir}</>}
          description={<>Desc: {f.weather.description}</>}
          isExternalLink
        />
      ))}
    </Grid>
  </>
)

export default StaticForeCasts

StaticForeCasts.getLayout = function getLayout(page: ReactElement) {
  return <MainLayout>{page}</MainLayout>
}
