import { ReactElement } from 'react'
import Head from 'next/head'
import type {
  GetServerSidePropsContext,
  GetServerSideProps,
  InferGetServerSidePropsType,
} from 'next'
import MainLayout from '@Layouts/MainLayout'

import CurrentObservationPanel from '@Organisms/CurrentObservationPanel/CurrentObservationPanel'
import { getObservationDetailsRequest } from '@Api/getObservationsDetails'

type DetailsPageProps = {
  /** Detailed data for observation panel and details panel */
  detailedObservation: GetDetailedForecatsResponse
}

export const getServerSideProps: GetServerSideProps<DetailsPageProps> = async (
  context: GetServerSidePropsContext
) => {
  const params = context.query.lat ? context.query : context.params
  console.log('getServerSideProps - params: ', params)

  const response: GetObservationDetailsAxiosResponse =
    await getObservationDetailsRequest(
      params as unknown as GetObservationDetailsRequestParams
    )

  return {
    props: {
      detailedObservation: response.data,
    },
  }
}

const DetailsPage: NextPageWithLayout<DetailsPageProps> = ({
  detailedObservation,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => (
  <>
    <Head>
      <title>Forecasts</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <CurrentObservationPanel data={detailedObservation} />
  </>
)
export default DetailsPage

DetailsPage.getLayout = (page: ReactElement) => <MainLayout>{page}</MainLayout>
